// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Aquatrols.iOS
{
	public partial class VwHeader : UIView
	{
		public VwHeader (IntPtr handle) : base (handle)
		{
		}
	}
}
